In [29]:
import ipynb
import amfm_decompy
import scipy
from scipy.optimize import curve_fit
from scipy.io import wavfile
from scipy import signal
from scipy.signal import butter, sosfiltfilt
import matplotlib.pyplot as plt
from matplotlib import pylab
import math
import pandas as pd
import numpy as np
import osascript
from gtts import gTTS 
import os 
import pyaudio
import wave
import keyboard  # using module keyboard
import soundfile as sf
import pyloudnorm as pyln
from sys import byteorder
from array import array
from struct import pack
import time
import subprocess
import pyttsx3
import tkinter
import librosa
import pysptk
import audiolazy
from ipynb.fs.full.concat_project import extract_data


# Constants

In [30]:
RATE = 22050

In [31]:
def get_data(filepath):
    data = np.load(filepath, allow_pickle=True)
    fs = RATE
    return data, fs

In [32]:
def remove_silence_from(amplitudes, threshold):
    silenced = []
    for x in amplitudes:
        if x >= threshold:
            silenced.append(x)
    return silenced

In [33]:
def get_LPCs(data):
    fs = RATE
#     plt.figure(0)
#     plt.plot(data)
    wavfile.write('temp_sound.wav', fs, np.divide(data, 50))
    data = np.float32(data)

In [34]:
extract_data('../../LDC2002S28.wav')

(array([array([6.65922541, 3.043437  , 0.0646772 , ..., 9.46914264, 8.8310075 ,
        6.55968461]),
        array([ 0.20685122, -0.44640086, -0.73763219, ..., -3.63786321,
        -0.65749809,  2.21309761]),
        array([ 5.16802409,  5.06485251,  4.81559807, ...,  9.23604344,
        10.90923279, 10.90916875]),
        array([-0.54716691, -1.20453263, -0.98415094, ..., -0.63981481,
        -0.91277903, -1.16274012]),
        array([ 2.83902298,  2.53642083,  2.02376076, ..., -3.45709609,
        -3.6581131 , -2.75565778]),
        array([-1.375852  , -0.92459957, -0.93158306, ...,  9.90087162,
        10.47005824,  9.68025406]),
        array([ 0.39026843,  2.08258668,  3.41347463, ..., -2.93927262,
        -5.47567736, -7.83828531]),
        array([-4.87563512, -3.85338697, -2.76020567, ..., -6.06387054,
        -5.94119107, -6.52908095]),
        array([-1.69095737, -2.70500305, -2.62980387, ..., 11.27583226,
        10.0928256 ,  8.42577878]),
        array([-2.85265812, -0.072